spring.application.name=stockalert

spring.datasource.url=jdbc:mysql://localhost:3306/stockalert_db
spring.datasource.username=root
spring.datasource.password=naga

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8080